### PR TITLE
Fix noarch

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@ltalirz the recipe to be no arch cannot depends on platform. So, it means that you can not use selectors like ``# [win]`` or linux and so on

**Comment by ltalirz** [comment]
thanks, I overlooked the selectors in the test

**Comment by marcelotrevisani** [comment]
You can merge it if you agree with my modifications
:)

**Comment by marcelotrevisani** [comment]
It should work now

**Comment by ltalirz** [comment]
Thank you so much for your super-fast help!
I wouldn't have thought that directory changes persist between test items - that makes things indeed much easier :)

**Comment by marcelotrevisani** [comment]
You are welcome, if you have any problem in the future, please ping us again! :)

**Pull request merged**
