### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge/help-python I believe there is a problem with this PR - everything seemed to build fine but the merge commit [does not show a CI symbol](https://github.com/conda-forge/aldjemy-feedstock/commits/master) and I believe it is not being uploaded [1].
Could you perhaps provide a suggestion on what may be going wrong here?

Short recap of what I did in this PR:

I recently noticed that for some reason the package was not available on `linux64`. I therefore
  * first re-rendered the feedstock
  * Since the linter suggested to add `noarch: True` (and I believe the conditions apply), I added it 
  * then re-rendered again

The build passed and I squashed & merged.

[1] I'm still unable to find it in the conda-forge channel
```
$ conda search -c conda-forge aldjemy
Loading channels: done
# Name                       Version           Build  Channel
aldjemy                        0.6.0          py27_0  conda-forge
aldjemy                        0.6.0          py35_0  conda-forge
aldjemy                        0.6.0          py36_0  conda-forge
aldjemy                        0.7.0          py27_0  conda-forge
aldjemy                        0.7.0          py35_0  conda-forge
aldjemy                        0.7.0          py36_0  conda-forge
aldjemy                        0.8.0          py27_0  conda-forge
aldjemy                        0.8.0       py27_1000  conda-forge
aldjemy                        0.8.0          py35_0  conda-forge
aldjemy                        0.8.0          py36_0  conda-forge
aldjemy                        0.8.0       py36_1000  conda-forge
aldjemy                        0.8.0       py37_1000  conda-forge
aldjemy                        0.9.0       py27_1000  conda-forge
aldjemy                        0.9.0       py36_1000  conda-forge
aldjemy                        0.9.0       py37_1000  conda-forge
aldjemy                        0.9.1          py27_0  conda-forge
aldjemy                        0.9.1          py36_0  conda-forge
aldjemy                        0.9.1          py37_0  conda-forge
```

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
I'd ping @conda-forge/core

**Comment by ltalirz** [comment]
Thanks!

**Comment by marcelotrevisani** [comment]
Already fixed with 
https://github.com/conda-forge/aldjemy-feedstock/pull/8

**Pull request merged**
